gantsign/ansible-role-oh-my-zsh

- .travis.yml
- ansible.cfg
- defaults/main.yml
- tasks/main.yml
- templates/zshrc.j2
- tests/inventory
- tests/test.yml
Role to download, install and configure oh-my-zsh.
> Implemented oh-my-zsh role

- .travis.yml
> Synchronized .travis.yml across roles

- tests/test_role.py
Can use simple array if there only a single param.
> Paramaeterized test syntax improvement

- tasks/debian-console-setup.yml
- tasks/main.yml
Improve separation of concerns.
> Moved console setup into separate file

- molecule.yml
It's still a supported version.
> Added Ubuntu Trusty to test matrix

- README.md
Added supported Ubuntu versions to `README.md`.
> Documented supported Ubuntu versions

- README.md
- meta/main.yml
- molecule.yml
* Include Debian 7 & 8 in test matrix.
* Add to Ansible metadata.
Enhancement: resolves #35
> Added support for Debian 7 & 8

- README.md
Added Ansible requirement to `README.md`.
> Documented Ansible requirement

- README.md
- meta/main.yml
- molecule.yml
- tasks/install.yml
- tasks/main.yml
- tests/test_role.py
* Added to test matrix
* Added to ansible metadata
* Added dependency support
Enhancement: resolves #39
> Added support for CentOS 7

- tests/test.yml
Using `with_items` is more concise.
> Merged creation of test users

- README.md
- meta/main.yml
- molecule.yml
- tests/test.yml
* Added to test matrix
* Added to Ansible metadata
* Added dnf package support
Enhancement: resolves #42
> Added support for Fedora 25

- molecule.yml
> Fixed Docker image name

- README.md
- meta/main.yml
- molecule.yml
- tasks/install.yml
- tests/test.yml
- tests/test_role.py
* Added to test matrix
* Added Ansble metadata
* Install dependencies with zypper
Enhancement: resolves #45
> Added support for OpenSUSE 42.2

- handlers/main.yml
- tasks/debian-console-setup.yml
To follow Ansible best practice.
> Moved dpkg-reconfigure to handler

- templates/zshrc.j2
Allow for a more verbose ansible_managed message.
> Added support for multiline ansible_managed

- molecule/default/playbook.yml
These are now provided out of the box by Molecule.
> Removed unnecessary test dependencies

- molecule/default/molecule.yml
To make the platforms easier to update.
> Made Molecule platform names more generic

- README.md
- meta/main.yml
- molecule/default/molecule.yml
> Added support for Debian Stretch

- README.md
- meta/main.yml
- molecule/default/molecule.yml
> Upgraded Fedora version to 28

- README.md
- meta/main.yml
- molecule/default/molecule.yml
> Upgraded openSUSE version to 15.0

- README.md
Most users will be better off with the Antigen role.
> Added link to gantsign.ansible_role_antigen role in README.md

- templates/zshrc.j2
Update default template used to create .zshrc file in the user directory
The content is from https://github.com/robbyrussell/oh-my-zsh/blob/master/templates/zshrc.zsh-template
> Update zshrc.j2 template with content from robbyrussell/oh-my-zsh

- README.md
- meta/main.yml
- molecule/default/molecule.yml
> Upgraded Fedora version to 31

- README.md
- meta/main.yml
- molecule/default/molecule.yml
> Upgraded openSUSE version to 15.1

- tasks/install.yml
> Optimized installation of dependencies

- tasks/install.yml
- templates/zshrc.j2
> Added loop variable names

- tasks/install.yml
> Added label for complex loop items

- README.md
- defaults/main.yml
- molecule/default/converge.yml
- molecule/default/tests/test_role.py
- tasks/install.yml
Useful for users specified at the playbook level instead of the role level.
> Added support for conditional install per user

- README.md
- meta/main.yml
- molecule/default/molecule.yml
Bullseye is the latest stable version of Debian.
> Increased upper Debian test version to Bullseye

- README.md
- meta/main.yml
- molecule/default/molecule.yml
> Upgraded test Fedora version to 35

- README.md
- meta/main.yml
- molecule/default/molecule.yml
> Upgraded openSUSE version to 15.3

- README.md
Antigen is no longer maintained.
> Removed link to Antigen role

- README.md
- defaults/main.yml
- molecule/default/converge.yml
- molecule/default/tests/test_role.py
- templates/zshrc.j2
This PR relates to #121 were a new var was required to set the update mode on the jinja template, this is a draft.
> New var to control update mode

- README.md
- defaults/main.yml
- molecule/default/converge.yml
- molecule/default/tests/test_role.py
- templates/zshrc.j2
For users who don't want updates disabled.
Enhancement: resolves #121
> Added variables for configuring update mode

- tasks/debian-console-setup.yml
- tasks/install.yml
- tasks/main.yml
> Changed to use fully qualified module names

- .yamllint
- README.md
- defaults/main.yml
- handlers/main.yml
- meta/main.yml
- molecule/default/converge.yml
- tasks/debian-console-setup.yml
- tasks/install.yml
- tasks/main.yml
- vars/main.yml
In preparation for Molecule upgrade.
> Fixed Ansible Lint warnings

- molecule/default/converge.yml
- molecule/default/molecule.yml
- tasks/install.yml
- tasks/main.yml
Support `inject_facts_as_vars: false`.
> Removed dependency on facts injected as vars

- README.md
- defaults/main.yml
- molecule/default/converge.yml
- molecule/default/tests/test_role.py
- tasks/install.yml
Useful for those with their own dotfiles.
Enhancement: resolves #160
> Added flag to disable writing zshrc
